services:
  provisioner:
    build: .
    image: nowage/ubuntu:ssh
    container_name: u1
    hostname: u1
    volumes:
      - ../root:/root
      - ~/df:/df
    environment:
      - TZ=Asia/Seoul
    tty: true
    ports:
      - "12222:22"
