FROM tensorflow/tensorflow
MAINTAINER The finfraTeam Project <nowage@gmail.com>

COPY ./install.sh /
RUN chmod 755 /install.sh
RUN bash /install.sh

# ENTRYPOINT ["/xx/sshd","sshd"]
# CMD /install.sh
