services:
  provisioner:
    build: .
    image: nowage/oraclelinux:ssh
    container_name: o1
    hostname: o1
    ports:
      - "22222:22"
    volumes:
      - ../root:/root
      - ~/df:/df
      - ~/_git:/git
    environment:
      - TZ=Asia/Seoul
    tty: true 
