services:
  provisioner:
    build: .
    image: nowage/sremsa-provisioner:ssh
    container_name: provisioner
    hostname: provisioner
    ports:
      - "32222:22"
    volumes:
      - ../root:/root
      - ${DF_PATH}:/df
    environment:
      - TZ=Asia/Seoul
    tty: true
